package cn.yutang.backend.pojo.po;

import java.io.Serializable;

public class Cookmethod implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethod.cm_id
     *
     * @mbg.generated
     */
    private Integer cmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethod.cm_name
     *
     * @mbg.generated
     */
    private String cmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethod.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethod.cm_id
     *
     * @return the value of CookMethod.cm_id
     *
     * @mbg.generated
     */
    public Integer getCmId() {
        return cmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethod.cm_id
     *
     * @param cmId the value for CookMethod.cm_id
     *
     * @mbg.generated
     */
    public void setCmId(Integer cmId) {
        this.cmId = cmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethod.cm_name
     *
     * @return the value of CookMethod.cm_name
     *
     * @mbg.generated
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethod.cm_name
     *
     * @param cmName the value for CookMethod.cm_name
     *
     * @mbg.generated
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethod.shop_id
     *
     * @return the value of CookMethod.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethod.shop_id
     *
     * @param shopId the value for CookMethod.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }
}