package cn.yutang.backend.pojo.po;

import java.util.Date;

public class Dinnertable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DinnerTable.tb_id
     *
     * @mbg.generated
     */
    private Integer tbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DinnerTable.tb_name
     *
     * @mbg.generated
     */
    private String tbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DinnerTable.tb_status
     *
     * @mbg.generated
     */
    private Integer tbStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DinnerTable.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DinnerTable.tb_id
     *
     * @return the value of DinnerTable.tb_id
     *
     * @mbg.generated
     */
    public Integer getTbId() {
        return tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DinnerTable.tb_id
     *
     * @param tbId the value for DinnerTable.tb_id
     *
     * @mbg.generated
     */
    public void setTbId(Integer tbId) {
        this.tbId = tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DinnerTable.tb_name
     *
     * @return the value of DinnerTable.tb_name
     *
     * @mbg.generated
     */
    public String getTbName() {
        return tbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DinnerTable.tb_name
     *
     * @param tbName the value for DinnerTable.tb_name
     *
     * @mbg.generated
     */
    public void setTbName(String tbName) {
        this.tbName = tbName == null ? null : tbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DinnerTable.tb_status
     *
     * @return the value of DinnerTable.tb_status
     *
     * @mbg.generated
     */
    public Integer getTbStatus() {
        return tbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DinnerTable.tb_status
     *
     * @param tbStatus the value for DinnerTable.tb_status
     *
     * @mbg.generated
     */
    public void setTbStatus(Integer tbStatus) {
        this.tbStatus = tbStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DinnerTable.order_date
     *
     * @return the value of DinnerTable.order_date
     *
     * @mbg.generated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DinnerTable.order_date
     *
     * @param orderDate the value for DinnerTable.order_date
     *
     * @mbg.generated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
}