package cn.yutang.backend.pojo.po;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.emp_id
     *
     * @mbg.generated
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.emp_name
     *
     * @mbg.generated
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.emp_nickname
     *
     * @mbg.generated
     */
    private String empNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.emp_password
     *
     * @mbg.generated
     */
    private String empPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.emp_authority
     *
     * @mbg.generated
     */
    private Integer empAuthority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.emp_tel
     *
     * @mbg.generated
     */
    private String empTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.emp_id
     *
     * @return the value of Employee.emp_id
     *
     * @mbg.generated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.emp_id
     *
     * @param empId the value for Employee.emp_id
     *
     * @mbg.generated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.emp_name
     *
     * @return the value of Employee.emp_name
     *
     * @mbg.generated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.emp_name
     *
     * @param empName the value for Employee.emp_name
     *
     * @mbg.generated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.emp_nickname
     *
     * @return the value of Employee.emp_nickname
     *
     * @mbg.generated
     */
    public String getEmpNickname() {
        return empNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.emp_nickname
     *
     * @param empNickname the value for Employee.emp_nickname
     *
     * @mbg.generated
     */
    public void setEmpNickname(String empNickname) {
        this.empNickname = empNickname == null ? null : empNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.emp_password
     *
     * @return the value of Employee.emp_password
     *
     * @mbg.generated
     */
    public String getEmpPassword() {
        return empPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.emp_password
     *
     * @param empPassword the value for Employee.emp_password
     *
     * @mbg.generated
     */
    public void setEmpPassword(String empPassword) {
        this.empPassword = empPassword == null ? null : empPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.emp_authority
     *
     * @return the value of Employee.emp_authority
     *
     * @mbg.generated
     */
    public Integer getEmpAuthority() {
        return empAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.emp_authority
     *
     * @param empAuthority the value for Employee.emp_authority
     *
     * @mbg.generated
     */
    public void setEmpAuthority(Integer empAuthority) {
        this.empAuthority = empAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.emp_tel
     *
     * @return the value of Employee.emp_tel
     *
     * @mbg.generated
     */
    public String getEmpTel() {
        return empTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.emp_tel
     *
     * @param empTel the value for Employee.emp_tel
     *
     * @mbg.generated
     */
    public void setEmpTel(String empTel) {
        this.empTel = empTel == null ? null : empTel.trim();
    }
}