package cn.yutang.backend.pojo.po;

public class Foodorderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.od_id
     *
     * @mbg.generated
     */
    private String odId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.or_id
     *
     * @mbg.generated
     */
    private String orId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.fd_id
     *
     * @mbg.generated
     */
    private String fdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.fd_count
     *
     * @mbg.generated
     */
    private Integer fdCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.od_id
     *
     * @return the value of FoodOrderDetail.od_id
     *
     * @mbg.generated
     */
    public String getOdId() {
        return odId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.od_id
     *
     * @param odId the value for FoodOrderDetail.od_id
     *
     * @mbg.generated
     */
    public void setOdId(String odId) {
        this.odId = odId == null ? null : odId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.or_id
     *
     * @return the value of FoodOrderDetail.or_id
     *
     * @mbg.generated
     */
    public String getOrId() {
        return orId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.or_id
     *
     * @param orId the value for FoodOrderDetail.or_id
     *
     * @mbg.generated
     */
    public void setOrId(String orId) {
        this.orId = orId == null ? null : orId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.fd_id
     *
     * @return the value of FoodOrderDetail.fd_id
     *
     * @mbg.generated
     */
    public String getFdId() {
        return fdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.fd_id
     *
     * @param fdId the value for FoodOrderDetail.fd_id
     *
     * @mbg.generated
     */
    public void setFdId(String fdId) {
        this.fdId = fdId == null ? null : fdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.fd_count
     *
     * @return the value of FoodOrderDetail.fd_count
     *
     * @mbg.generated
     */
    public Integer getFdCount() {
        return fdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.fd_count
     *
     * @param fdCount the value for FoodOrderDetail.fd_count
     *
     * @mbg.generated
     */
    public void setFdCount(Integer fdCount) {
        this.fdCount = fdCount;
    }
}