package cn.yutang.backend.pojo.po;

public class Foodtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodType.ft_id
     *
     * @mbg.generated
     */
    private Integer ftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodType.ft_name
     *
     * @mbg.generated
     */
    private String ftName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodType.ft_id
     *
     * @return the value of FoodType.ft_id
     *
     * @mbg.generated
     */
    public Integer getFtId() {
        return ftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodType.ft_id
     *
     * @param ftId the value for FoodType.ft_id
     *
     * @mbg.generated
     */
    public void setFtId(Integer ftId) {
        this.ftId = ftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodType.ft_name
     *
     * @return the value of FoodType.ft_name
     *
     * @mbg.generated
     */
    public String getFtName() {
        return ftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodType.ft_name
     *
     * @param ftName the value for FoodType.ft_name
     *
     * @mbg.generated
     */
    public void setFtName(String ftName) {
        this.ftName = ftName == null ? null : ftName.trim();
    }
}