package cn.yutang.backend.pojo.po;

import java.util.Date;

public class Foodorders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrders.or_id
     *
     * @mbg.generated
     */
    private String orId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrders.tb_id
     *
     * @mbg.generated
     */
    private Integer tbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrders.or_beginTime
     *
     * @mbg.generated
     */
    private Date orBegintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrders.or_endTime
     *
     * @mbg.generated
     */
    private Date orEndtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrders.or_status
     *
     * @mbg.generated
     */
    private Integer orStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrders.or_id
     *
     * @return the value of FoodOrders.or_id
     *
     * @mbg.generated
     */
    public String getOrId() {
        return orId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrders.or_id
     *
     * @param orId the value for FoodOrders.or_id
     *
     * @mbg.generated
     */
    public void setOrId(String orId) {
        this.orId = orId == null ? null : orId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrders.tb_id
     *
     * @return the value of FoodOrders.tb_id
     *
     * @mbg.generated
     */
    public Integer getTbId() {
        return tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrders.tb_id
     *
     * @param tbId the value for FoodOrders.tb_id
     *
     * @mbg.generated
     */
    public void setTbId(Integer tbId) {
        this.tbId = tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrders.or_beginTime
     *
     * @return the value of FoodOrders.or_beginTime
     *
     * @mbg.generated
     */
    public Date getOrBegintime() {
        return orBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrders.or_beginTime
     *
     * @param orBegintime the value for FoodOrders.or_beginTime
     *
     * @mbg.generated
     */
    public void setOrBegintime(Date orBegintime) {
        this.orBegintime = orBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrders.or_endTime
     *
     * @return the value of FoodOrders.or_endTime
     *
     * @mbg.generated
     */
    public Date getOrEndtime() {
        return orEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrders.or_endTime
     *
     * @param orEndtime the value for FoodOrders.or_endTime
     *
     * @mbg.generated
     */
    public void setOrEndtime(Date orEndtime) {
        this.orEndtime = orEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrders.or_status
     *
     * @return the value of FoodOrders.or_status
     *
     * @mbg.generated
     */
    public Integer getOrStatus() {
        return orStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrders.or_status
     *
     * @param orStatus the value for FoodOrders.or_status
     *
     * @mbg.generated
     */
    public void setOrStatus(Integer orStatus) {
        this.orStatus = orStatus;
    }
}