package cn.yutang.backend.pojo.po;

import java.io.Serializable;

public class PayMethod implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayMethod.pm_id
     *
     * @mbg.generated
     */
    private Integer pmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayMethod.pm_name
     *
     * @mbg.generated
     */
    private String pmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PayMethod
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayMethod.pm_id
     *
     * @return the value of PayMethod.pm_id
     *
     * @mbg.generated
     */
    public Integer getPmId() {
        return pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayMethod.pm_id
     *
     * @param pmId the value for PayMethod.pm_id
     *
     * @mbg.generated
     */
    public void setPmId(Integer pmId) {
        this.pmId = pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayMethod.pm_name
     *
     * @return the value of PayMethod.pm_name
     *
     * @mbg.generated
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayMethod.pm_name
     *
     * @param pmName the value for PayMethod.pm_name
     *
     * @mbg.generated
     */
    public void setPmName(String pmName) {
        this.pmName = pmName == null ? null : pmName.trim();
    }
}