package cn.yutang.backend.pojo.po;

import java.util.Date;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_nickname
     *
     * @mbg.generated
     */
    private String shopNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_password
     *
     * @mbg.generated
     */
    private String shopPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_tel
     *
     * @mbg.generated
     */
    private String shopTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_status
     *
     * @mbg.generated
     */
    private Integer shopStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_logo
     *
     * @mbg.generated
     */
    private String shopLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_openTime
     *
     * @mbg.generated
     */
    private String shopOpentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.shop_closeTime
     *
     * @mbg.generated
     */
    private String shopClosetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.contract_term
     *
     * @mbg.generated
     */
    private Integer contractTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.contract_startTime
     *
     * @mbg.generated
     */
    private Date contractStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shop.contract_endTime
     *
     * @mbg.generated
     */
    private Date contractEndtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_id
     *
     * @return the value of Shop.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_id
     *
     * @param shopId the value for Shop.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_name
     *
     * @return the value of Shop.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_name
     *
     * @param shopName the value for Shop.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_nickname
     *
     * @return the value of Shop.shop_nickname
     *
     * @mbg.generated
     */
    public String getShopNickname() {
        return shopNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_nickname
     *
     * @param shopNickname the value for Shop.shop_nickname
     *
     * @mbg.generated
     */
    public void setShopNickname(String shopNickname) {
        this.shopNickname = shopNickname == null ? null : shopNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_password
     *
     * @return the value of Shop.shop_password
     *
     * @mbg.generated
     */
    public String getShopPassword() {
        return shopPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_password
     *
     * @param shopPassword the value for Shop.shop_password
     *
     * @mbg.generated
     */
    public void setShopPassword(String shopPassword) {
        this.shopPassword = shopPassword == null ? null : shopPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_tel
     *
     * @return the value of Shop.shop_tel
     *
     * @mbg.generated
     */
    public String getShopTel() {
        return shopTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_tel
     *
     * @param shopTel the value for Shop.shop_tel
     *
     * @mbg.generated
     */
    public void setShopTel(String shopTel) {
        this.shopTel = shopTel == null ? null : shopTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_status
     *
     * @return the value of Shop.shop_status
     *
     * @mbg.generated
     */
    public Integer getShopStatus() {
        return shopStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_status
     *
     * @param shopStatus the value for Shop.shop_status
     *
     * @mbg.generated
     */
    public void setShopStatus(Integer shopStatus) {
        this.shopStatus = shopStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_logo
     *
     * @return the value of Shop.shop_logo
     *
     * @mbg.generated
     */
    public String getShopLogo() {
        return shopLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_logo
     *
     * @param shopLogo the value for Shop.shop_logo
     *
     * @mbg.generated
     */
    public void setShopLogo(String shopLogo) {
        this.shopLogo = shopLogo == null ? null : shopLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_openTime
     *
     * @return the value of Shop.shop_openTime
     *
     * @mbg.generated
     */
    public String getShopOpentime() {
        return shopOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_openTime
     *
     * @param shopOpentime the value for Shop.shop_openTime
     *
     * @mbg.generated
     */
    public void setShopOpentime(String shopOpentime) {
        this.shopOpentime = shopOpentime == null ? null : shopOpentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.shop_closeTime
     *
     * @return the value of Shop.shop_closeTime
     *
     * @mbg.generated
     */
    public String getShopClosetime() {
        return shopClosetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.shop_closeTime
     *
     * @param shopClosetime the value for Shop.shop_closeTime
     *
     * @mbg.generated
     */
    public void setShopClosetime(String shopClosetime) {
        this.shopClosetime = shopClosetime == null ? null : shopClosetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.contract_term
     *
     * @return the value of Shop.contract_term
     *
     * @mbg.generated
     */
    public Integer getContractTerm() {
        return contractTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.contract_term
     *
     * @param contractTerm the value for Shop.contract_term
     *
     * @mbg.generated
     */
    public void setContractTerm(Integer contractTerm) {
        this.contractTerm = contractTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.contract_startTime
     *
     * @return the value of Shop.contract_startTime
     *
     * @mbg.generated
     */
    public Date getContractStarttime() {
        return contractStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.contract_startTime
     *
     * @param contractStarttime the value for Shop.contract_startTime
     *
     * @mbg.generated
     */
    public void setContractStarttime(Date contractStarttime) {
        this.contractStarttime = contractStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shop.contract_endTime
     *
     * @return the value of Shop.contract_endTime
     *
     * @mbg.generated
     */
    public Date getContractEndtime() {
        return contractEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shop.contract_endTime
     *
     * @param contractEndtime the value for Shop.contract_endTime
     *
     * @mbg.generated
     */
    public void setContractEndtime(Date contractEndtime) {
        this.contractEndtime = contractEndtime;
    }
}