package cn.yutang.client.dao;

import cn.yutang.client.pojo.po.FoodOrders;
import cn.yutang.client.pojo.po.FoodOrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    long countByExample(FoodOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int deleteByExample(FoodOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int insert(FoodOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int insertSelective(FoodOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    List<FoodOrders> selectByExample(FoodOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    FoodOrders selectByPrimaryKey(String orId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FoodOrders record, @Param("example") FoodOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FoodOrders record, @Param("example") FoodOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FoodOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FoodOrders record);
}