package cn.yutang.client.dao;

import cn.yutang.client.pojo.po.FoodType;
import cn.yutang.client.pojo.po.FoodTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    long countByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int deleteByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int insert(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int insertSelective(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    List<FoodType> selectByExample(FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    FoodType selectByPrimaryKey(Integer ftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FoodType record, @Param("example") FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FoodType record, @Param("example") FoodTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FoodType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FoodType record);
}