package cn.yutang.client.pojo.po;

import java.io.Serializable;

public class CookMethodDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethodDetail.cmd_id
     *
     * @mbg.generated
     */
    private Integer cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethodDetail.cmd_name
     *
     * @mbg.generated
     */
    private String cmdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethodDetail.cm_id
     *
     * @mbg.generated
     */
    private Integer cmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CookMethodDetail.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethodDetail.cmd_id
     *
     * @return the value of CookMethodDetail.cmd_id
     *
     * @mbg.generated
     */
    public Integer getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethodDetail.cmd_id
     *
     * @param cmdId the value for CookMethodDetail.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(Integer cmdId) {
        this.cmdId = cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethodDetail.cmd_name
     *
     * @return the value of CookMethodDetail.cmd_name
     *
     * @mbg.generated
     */
    public String getCmdName() {
        return cmdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethodDetail.cmd_name
     *
     * @param cmdName the value for CookMethodDetail.cmd_name
     *
     * @mbg.generated
     */
    public void setCmdName(String cmdName) {
        this.cmdName = cmdName == null ? null : cmdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethodDetail.cm_id
     *
     * @return the value of CookMethodDetail.cm_id
     *
     * @mbg.generated
     */
    public Integer getCmId() {
        return cmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethodDetail.cm_id
     *
     * @param cmId the value for CookMethodDetail.cm_id
     *
     * @mbg.generated
     */
    public void setCmId(Integer cmId) {
        this.cmId = cmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CookMethodDetail.shop_id
     *
     * @return the value of CookMethodDetail.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CookMethodDetail.shop_id
     *
     * @param shopId the value for CookMethodDetail.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}