package cn.yutang.client.pojo.po;

import java.io.Serializable;
import java.util.Date;

public class FoodOrderDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.odt_id
     *
     * @mbg.generated
     */
    private String odtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.or_id
     *
     * @mbg.generated
     */
    private String orId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.fd_id
     *
     * @mbg.generated
     */
    private Integer fdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.fd_count
     *
     * @mbg.generated
     */
    private Integer fdCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.cook_method
     *
     * @mbg.generated
     */
    private String cookMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.odt_time
     *
     * @mbg.generated
     */
    private Date odtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.odt_type
     *
     * @mbg.generated
     */
    private Integer odtType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FoodOrderDetail.emp_id
     *
     * @mbg.generated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FoodOrderDetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.odt_id
     *
     * @return the value of FoodOrderDetail.odt_id
     *
     * @mbg.generated
     */
    public String getOdtId() {
        return odtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.odt_id
     *
     * @param odtId the value for FoodOrderDetail.odt_id
     *
     * @mbg.generated
     */
    public void setOdtId(String odtId) {
        this.odtId = odtId == null ? null : odtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.or_id
     *
     * @return the value of FoodOrderDetail.or_id
     *
     * @mbg.generated
     */
    public String getOrId() {
        return orId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.or_id
     *
     * @param orId the value for FoodOrderDetail.or_id
     *
     * @mbg.generated
     */
    public void setOrId(String orId) {
        this.orId = orId == null ? null : orId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.fd_id
     *
     * @return the value of FoodOrderDetail.fd_id
     *
     * @mbg.generated
     */
    public Integer getFdId() {
        return fdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.fd_id
     *
     * @param fdId the value for FoodOrderDetail.fd_id
     *
     * @mbg.generated
     */
    public void setFdId(Integer fdId) {
        this.fdId = fdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.fd_count
     *
     * @return the value of FoodOrderDetail.fd_count
     *
     * @mbg.generated
     */
    public Integer getFdCount() {
        return fdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.fd_count
     *
     * @param fdCount the value for FoodOrderDetail.fd_count
     *
     * @mbg.generated
     */
    public void setFdCount(Integer fdCount) {
        this.fdCount = fdCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.cook_method
     *
     * @return the value of FoodOrderDetail.cook_method
     *
     * @mbg.generated
     */
    public String getCookMethod() {
        return cookMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.cook_method
     *
     * @param cookMethod the value for FoodOrderDetail.cook_method
     *
     * @mbg.generated
     */
    public void setCookMethod(String cookMethod) {
        this.cookMethod = cookMethod == null ? null : cookMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.shop_id
     *
     * @return the value of FoodOrderDetail.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.shop_id
     *
     * @param shopId the value for FoodOrderDetail.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.odt_time
     *
     * @return the value of FoodOrderDetail.odt_time
     *
     * @mbg.generated
     */
    public Date getOdtTime() {
        return odtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.odt_time
     *
     * @param odtTime the value for FoodOrderDetail.odt_time
     *
     * @mbg.generated
     */
    public void setOdtTime(Date odtTime) {
        this.odtTime = odtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.odt_type
     *
     * @return the value of FoodOrderDetail.odt_type
     *
     * @mbg.generated
     */
    public Integer getOdtType() {
        return odtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.odt_type
     *
     * @param odtType the value for FoodOrderDetail.odt_type
     *
     * @mbg.generated
     */
    public void setOdtType(Integer odtType) {
        this.odtType = odtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FoodOrderDetail.emp_id
     *
     * @return the value of FoodOrderDetail.emp_id
     *
     * @mbg.generated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FoodOrderDetail.emp_id
     *
     * @param empId the value for FoodOrderDetail.emp_id
     *
     * @mbg.generated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
}