package cn.yutang.client.pojo.po;

import java.io.Serializable;

public class PayDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayDetail.pd_id
     *
     * @mbg.generated
     */
    private String pdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayDetail.pm_id
     *
     * @mbg.generated
     */
    private Integer pmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayDetail.pd_ammount
     *
     * @mbg.generated
     */
    private Double pdAmmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayDetail.or_id
     *
     * @mbg.generated
     */
    private String orId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PayDetail.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PayDetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayDetail.pd_id
     *
     * @return the value of PayDetail.pd_id
     *
     * @mbg.generated
     */
    public String getPdId() {
        return pdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayDetail.pd_id
     *
     * @param pdId the value for PayDetail.pd_id
     *
     * @mbg.generated
     */
    public void setPdId(String pdId) {
        this.pdId = pdId == null ? null : pdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayDetail.pm_id
     *
     * @return the value of PayDetail.pm_id
     *
     * @mbg.generated
     */
    public Integer getPmId() {
        return pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayDetail.pm_id
     *
     * @param pmId the value for PayDetail.pm_id
     *
     * @mbg.generated
     */
    public void setPmId(Integer pmId) {
        this.pmId = pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayDetail.pd_ammount
     *
     * @return the value of PayDetail.pd_ammount
     *
     * @mbg.generated
     */
    public Double getPdAmmount() {
        return pdAmmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayDetail.pd_ammount
     *
     * @param pdAmmount the value for PayDetail.pd_ammount
     *
     * @mbg.generated
     */
    public void setPdAmmount(Double pdAmmount) {
        this.pdAmmount = pdAmmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayDetail.or_id
     *
     * @return the value of PayDetail.or_id
     *
     * @mbg.generated
     */
    public String getOrId() {
        return orId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayDetail.or_id
     *
     * @param orId the value for PayDetail.or_id
     *
     * @mbg.generated
     */
    public void setOrId(String orId) {
        this.orId = orId == null ? null : orId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PayDetail.shop_id
     *
     * @return the value of PayDetail.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PayDetail.shop_id
     *
     * @param shopId the value for PayDetail.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}