package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Cookmethod;
import cn.yutang.backend.pojo.po.CookmethodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CookmethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    long countByExample(CookmethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int deleteByExample(CookmethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int insert(Cookmethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int insertSelective(Cookmethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    List<Cookmethod> selectByExample(CookmethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    Cookmethod selectByPrimaryKey(Integer cmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cookmethod record, @Param("example") CookmethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cookmethod record, @Param("example") CookmethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cookmethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethod
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cookmethod record);
}