package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Cookmethoddetail;
import cn.yutang.backend.pojo.po.CookmethoddetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CookmethoddetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    long countByExample(CookmethoddetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int deleteByExample(CookmethoddetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int insert(Cookmethoddetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int insertSelective(Cookmethoddetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    List<Cookmethoddetail> selectByExample(CookmethoddetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    Cookmethoddetail selectByPrimaryKey(Integer cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Cookmethoddetail record, @Param("example") CookmethoddetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Cookmethoddetail record, @Param("example") CookmethoddetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cookmethoddetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CookMethodDetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cookmethoddetail record);
}