package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Dinnertable;
import cn.yutang.backend.pojo.po.DinnertableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DinnertableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    long countByExample(DinnertableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int deleteByExample(DinnertableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int insert(Dinnertable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int insertSelective(Dinnertable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    List<Dinnertable> selectByExample(DinnertableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    Dinnertable selectByPrimaryKey(Integer tbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dinnertable record, @Param("example") DinnertableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dinnertable record, @Param("example") DinnertableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dinnertable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dinnertable record);
}