package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Dinnertabletype;
import cn.yutang.backend.pojo.po.DinnertabletypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DinnertabletypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    long countByExample(DinnertabletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int deleteByExample(DinnertabletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int insert(Dinnertabletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int insertSelective(Dinnertabletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    List<Dinnertabletype> selectByExample(DinnertabletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    Dinnertabletype selectByPrimaryKey(Integer ttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dinnertabletype record, @Param("example") DinnertabletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dinnertabletype record, @Param("example") DinnertabletypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dinnertabletype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTableType
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dinnertabletype record);
}