package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.DinnerTable;
import cn.yutang.backend.pojo.po.DinnerTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DinnerTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    long countByExample(DinnerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int deleteByExample(DinnerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int insert(DinnerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int insertSelective(DinnerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    List<DinnerTable> selectByExample(DinnerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    DinnerTable selectByPrimaryKey(Integer tbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DinnerTable record, @Param("example") DinnerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DinnerTable record, @Param("example") DinnerTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DinnerTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DinnerTable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DinnerTable record);
}