package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Foodtype;
import cn.yutang.backend.pojo.po.FoodtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    long countByExample(FoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int deleteByExample(FoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int insert(Foodtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int insertSelective(Foodtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    List<Foodtype> selectByExample(FoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    Foodtype selectByPrimaryKey(Integer ftId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Foodtype record, @Param("example") FoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Foodtype record, @Param("example") FoodtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Foodtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodType
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Foodtype record);
}