package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Foodorders;
import cn.yutang.backend.pojo.po.FoodordersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    long countByExample(FoodordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int deleteByExample(FoodordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int insert(Foodorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int insertSelective(Foodorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    List<Foodorders> selectByExample(FoodordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    Foodorders selectByPrimaryKey(String orId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Foodorders record, @Param("example") FoodordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Foodorders record, @Param("example") FoodordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Foodorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FoodOrders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Foodorders record);
}