package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.dto.Page;
import cn.yutang.backend.pojo.po.Food;
import cn.yutang.backend.pojo.po.FoodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    long countByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int deleteByExample(FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int insert(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int insertSelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     * @param example
     */
    List<Food> selectByExample(Page example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    Food selectByPrimaryKey(Integer fdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Food record, @Param("example") FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Food record, @Param("example") FoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Food
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Food record);

}