package cn.yutang.backend.dao;

import cn.yutang.backend.pojo.po.Shop;
import cn.yutang.backend.pojo.po.ShopExample;
import cn.yutang.backend.pojo.po.ShopWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    long countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int insert(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int insertSelective(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    List<ShopWithBLOBs> selectByExampleWithBLOBs(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    ShopWithBLOBs selectByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopWithBLOBs record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ShopWithBLOBs record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ShopWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shop record);
}